### ISSUE TITLE
Add programMap transformation to convert program name --> classification code

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/logical-outcomes#3]
We need to add transformation to L64 to convert program name (i.e., `'Development Other'`) to the appropriate classification code (i.e., `'05. DEV: Other'`) ...
https://github.com/OpenFn/logical-outcomes/blob/ae64fbbd9325dc0c306d797c90f6822bb5a36124/createTEI_care_reach.js#L62-L64
[See L2-18](https://github.com/OpenFn/logical-outcomes/blob/master/createTEI_care_reach.js#L2-L18) for the list of program classification mappings: 
```
const programMap = {
    "Humanitarian Sexual, Reproductive and Maternal Health (SRMH)":
      "09. HUM: SRMH",
    "Humanitarian A Life Free From Violence (GBV)": "08. HUM: LFFV",
    "Humanitarian Food & Nutrition Security and Resilience to Climate Change":
      "07. HUM: FNSCCR",
    "Humanitarian Access to and Control over Economic Resources":
      "06. HUM: Economic",
    "Humanitarian Other": "10. HUM: Other",
    "Development Sexual, Reproductive and Maternal Health (SRMH)":
      "04. DEV: SRMH",
    "Development A Life Free From Violence (GBV)": "03. DEV: LFFV",
    "Development Food & Nutrition Security and Resilience to Climate Change":
      "02. DEV: FNSCCR",
    "Development Access to and Control over Economic Resources":
      "01. DEV: Economic",
    "Development Other": "05. DEV: Other",
  };
```

To test...
1. Use [this sample data](https://github.com/OpenFn/logical-outcomes/blob/master/sample_data/csv-reach.json) (and see LP for creds - LO DHIS2 - CARE PIIRS)
2. Verify output in DHIS2: Run the job to create a new `tei` . Then plug the new `tei` Id into the below URL...and should see a TEI with 'Program Type Classification' in DHIS2: 
https://dev.piirs.care.org/dhis-web-tracker-capture/index.html#/dashboard?tei=WPMNJJK2tKx&program=SHRBw9XXHFk&ou=XywB8DSeyUJ

See DHIS2 option set for metadata config: https://dev.piirs.care.org/dhis-web-maintenance/index.html#/edit/otherSection/optionSet/I9y8KKXICyj/options

**Comment by taylordowns2000** [comment]
This is done and tested.
![image](https://user-images.githubusercontent.com/8732845/87788513-baebfa00-c7fa-11ea-99b8-8f773768d036.png)
