### ISSUE TITLE
upsertTEI job fails with error `414 Request-URI Too Large`

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/logical-outcomes#9]
## Background
Trying upsert TrackEntityInstances in a test DHIS2 instance for a client - should be a very quick upload job, but I am encountering roadblocks. I am following [the API docs](https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-master/tracker.html#webapi_create_enroll_tei_create_event) and feel good about how my payload is looking. 

I am trying upsert a single TEI, a related enrollment, and an event related to that program enrollment. 

## Issue
The adaptor seems to be sending my desired HTTP request body as parameters in the request it sends to the API. 
See run failure: https://www.openfn.org/projects/georgi-s-project/runs/062e0d67-bf56-7975-8b95-b91ab4a13600

## adaptor
`language-dhis2@3.0.5`

## state
configuration: See LP for `Logical Outcomes DHIS2 Test Instance - CARE`
data:  https://www.openfn.org/projects/georgi-s-project/messages/062e0d60-b07f-7337-88e3-1397f4521b66

## expression
https://github.com/OpenFn/logical-outcomes/blob/master/care/upsertTEI_ImpactValidStage.js

## To test
This is a test instance, feel free to play around with this job and use this sample state.data to post to the provided instance.

**Comment by taylordowns2000** [comment]
At first glance, seeing this: https://community.dhis2.org/t/414-request-uri-too-large/2698

Yes... ok, so this is doing an upsert and the first step of the upsert is to check to see if this thing exists. So it's failing on the `get` when it passes the entire payload as query parameters.

More to come...

**Comment by taylordowns2000** [comment]
@aleksa-krolls , this looks good (though now we've got a [409](https://www.openfn.org/projects/georgi-s-project/runs/062e0e3d-24aa-70eb-8281-7de225d915c2)).

the issue was that [upsert](https://openfn.github.io/language-dhis2/module-Adaptor.upsert.html) takes a query for its second argument: `upsert(resourceType, query, data, options, callback)` and we were passing what _should have been_ `data` as `query` — hence the "request too long" bit.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 even with your fix, nothing is being returned for `data`... showing as `undefined` in the logs and therefore failing to upsert. See run failure: https://www.openfn.org/projects/georgi-s-project/runs/062e11f0-8df6-73d9-911d-250edcbed2b3
```
url: 'https://testing.piirs.care.org/api/trackedEntityInstances',
    params: {},
    data: undefined
```

**Comment by taylordowns2000** [comment]
@aleksa-krolls , I've added [these two lines](https://github.com/OpenFn/logical-outcomes/blob/master/care/upsertTEI_ImpactValidStage.js#L4-L5) and it looks good to me, though new errors arising.

the trick was that these 409s (i included in the comments) were 409s for the `GET` request, not for the subsequent `create` or `update`. There's no data in the get, but it still is asking you to specify `ou` and `trackedEntityType` in the query
